新增rtp udp收流增加丢包率
ZLMediaKit/ZLMediaKit pull request #1829
Opened 2022-07-26 03:36 UTC by dcan123

1.rtp方式udp收流没有丢包率判断，无法追踪视频画面花屏是否由于网络原因。

2022-07-26 03:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ZLMediaKit/ZLMediaKit?pullRequest=1829) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ZLMediaKit/ZLMediaKit?pullRequest=1829) before we can accept your contribution.<br/><hr/>**dingcan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ZLMediaKit/ZLMediaKit?pullRequest=1829) it.</sub>

2022-07-26 03:40 UTC, xia-chu commented
麻烦先签署下cla协议

2022-07-26 05:02 UTC, wasphin requested changes

2022-07-26 06:19 UTC, dcan123 commented on src/Rtp/RtpProcess.cpp
> +        return help->geLostInterval() * 100 / expected;
父类接口返回值为int

2022-07-26 07:01 UTC, dcan123 reviewed
添加代码风格

2022-07-26 10:16 UTC, dcan123 commented
已经修改好了，可以合并吗

2022-07-26 10:51 UTC, wasphin requested changes

2022-07-26 10:51 UTC, wasphin commented on src/Rtp/RtpProcess.cpp
> +void RtpProcess::setHelper(const std::weak_ptr<RtcpContext> help){
这里 const 就不能用了。`{` 前有空格的。

2022-07-26 10:51 UTC, wasphin commented on src/Rtp/RtpProcess.cpp
> +	 if(!help){
`if` 后以及 `{` 前加一下空格吧。

2022-07-27 08:38 UTC, wasphin commented on src/Rtp/RtpProcess.cpp
> +     auto expected =  help->getExpectedPacketsInterval();
`=` 号右边还多一个空格哈。

2022-07-27 08:39 UTC, wasphin commented
Android 的 action 好像不是很稳定，出现两次没识别到 ndk 的现象。

2022-07-27 08:46 UTC, dcan123 commented
我修改的内容，跟系统没有关系吧，

2022-07-27 09:05 UTC, wasphin commented
> 我修改的内容，跟系统没有关系吧，

没关系，是 CI 的问题

2022-07-28 06:17 UTC, merged

2022-07-28 06:20 UTC, xia-chu commented
合入了 我觉得没问题了 不过应该squash合入的